# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    defaults:
      run:
        shell: bash
        working-directory: /data/chungguo.me
    timeout-minutes: 30

    runs-on: [self-hosted]


    steps:
    - name: 切换分支
      uses: actions/checkout@v2.3.4

    - name: 安装依赖
      run: npm install
      
    - name: 构建
      run: npm run build
    
    - name: 重启
      run: pm2 restart chungguo