# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [ main ]

jobs:
  OracleSeoulFD1:
    defaults:
      run:
        shell: bash
    runs-on: [FD1]
    env:
        NODE_OPTIONS: --max-old-space-size=1024
    steps:
    - name: 切换分支
      uses: actions/checkout@v2.3.4
    - name: 安装依赖
      run: yarn install
    - name: 设置环境变量
      run: |
        echo NEXT_PUBLIC_FIREBASE_CONFIG="$FIREBASE_CONFIG" > .env.local
        echo NEXT_PUBLIC_SS_USER_WHITELIST="$SS_USER_WHITELIST" >> .env.local
        echo NEXT_PUBLIC_SS_CONFIG_LIST="$SS_CONFIG_LIST" >> .env.local
      shell: bash
      env:
        FIREBASE_CONFIG : ${{secrets.FIREBASE_CONFIG}}
        SS_USER_WHITELIST : ${{secrets.SS_USER_WHITELIST}}
        SS_CONFIG_LIST : ${{secrets.SS_CONFIG_LIST}}
    - name: 构建
      run: yarn build
    - name: 重启
      run: pm2 restart chungguo || pm2 start yarn --name chungguo -- start

  OracleSeoulFD2:
    needs: OracleSeoulFD1
    defaults:
      run:
        shell: bash
    runs-on: [FD2]
    env:
        NODE_OPTIONS: --max-old-space-size=1024
    steps:
    - name: 切换分支
      uses: actions/checkout@v2.3.4
    - name: 安装依赖
      run: yarn install
    - name: 设置环境变量
      run: |
        echo NEXT_PUBLIC_FIREBASE_CONFIG="$FIREBASE_CONFIG" > .env.local
        echo NEXT_PUBLIC_SS_USER_WHITELIST="$SS_USER_WHITELIST" >> .env.local
        echo NEXT_PUBLIC_SS_CONFIG_LIST="$SS_CONFIG_LIST" >> .env.local
      shell: bash
      env:
        FIREBASE_CONFIG : ${{secrets.FIREBASE_CONFIG}}
        SS_USER_WHITELIST : ${{secrets.SS_USER_WHITELIST}}
        SS_CONFIG_LIST : ${{secrets.SS_CONFIG_LIST}}
    - name: 构建
      run: yarn build
    - name: 重启
      run: pm2 restart chungguo || pm2 start yarn --name chungguo -- start
