# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [ main ]

jobs:
  TencentHK:
    defaults:
      run:
        shell: bash
        working-directory: /data/chungguo.me
    runs-on: [TencentHK]
    steps:
    - name: 切换分支
      uses: actions/checkout@v2.3.4
    - name: 拉取代吗
      uses: git pull
    - name: 安装依赖
      run: npm install
    - name: 构建
      run: set NODE_OPTIONS=--max-old-space-size=2048 && npm run build
    - name: 重启
      run: pm2 restart chungguo

  OracleSeoul:
    defaults:
      run:
        shell: bash
        working-directory: /data/chungguo.me
    runs-on: [OracleSeoul]
    steps:
    - name: 切换分支
      uses: actions/checkout@v2.3.4
    - name: 拉取代吗
      uses: git pull
    - name: 安装依赖
      run: npm install
    - name: 构建
      run: set NODE_OPTIONS=--max-old-space-size=2048 && npm run build
    - name: 重启
      run: pm2 restart chungguo