# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [main]
  issues:
    types: [closed]

jobs:
  deploy:
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.instance }}
    strategy:
      matrix:
        instance: [instance132, instance152]
    env:
      NODE_OPTIONS: --max-old-space-size=1024
    steps:
      - name: 切换分支
        uses: actions/checkout@v2.3.4
      - name: 安装依赖
        run: npm install
      - name: 设置环境变量
        run: |
          echo NEXT_PUBLIC_FIREBASE_CONFIG="$FIREBASE_CONFIG" > .env.local
        shell: bash
        env:
          FIREBASE_CONFIG: ${{secrets.FIREBASE_CONFIG}}
      - name: 构建
        run: npm run build
      - name: 重启
        run: pm2 restart chungguo || pm2 start npm --name chungguo -- run start