# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [ main ]

jobs:
  TencentHKTC1:
    defaults:
      run:
        shell: bash
    runs-on: [TC1]
    steps:
    - name: 切换分支
      uses: actions/checkout@v2.3.4
    - name: 安装依赖
      run: yarn install
    - name: 构建
      run: set NODE_OPTIONS=--max-old-space-size=1024 && yarn build
    - name: 重启
      run: pm2 delete chungguo || pm2 start yarn --name chungguo -- start

  OracleSeoulFD1:
    defaults:
      run:
        shell: bash
    runs-on: [FD1]
    steps:
    - name: 切换分支
      uses: actions/checkout@v2.3.4
    - name: 安装依赖
      run: yarn install
    - name: 构建
      run: set NODE_OPTIONS=--max-old-space-size=1024 && yarn build
    - name: 重启
      run: pm2 delete chungguo || pm2 start yarn --name chungguo -- start

  OracleSeoulFD2:
    defaults:
      run:
        shell: bash
    runs-on: [FD2]
    steps:
    - name: 切换分支
      uses: actions/checkout@v2.3.4
    - name: 安装依赖
      run: yarn install
    - name: 构建
      run: set NODE_OPTIONS=--max-old-space-size=1024 && yarn build
    - name: 重启
      run: pm2 delete chungguo || pm2 start yarn --name chungguo -- start