name: Deploy To Tencent Virtual Cloud

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@main

      - name: Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: npm
        run: |
          npm install
          npm run build
      
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2
        env:
          # 本地.ssh文件下的私钥id_rsa，存在secrets的TOKEN中
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }} 
          # 复制操作的参数。"-avzr --delete"意味部署时清空服务器目标目录下的文件
          ARGS: "-avzr --delete" 
          # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
          SOURCE: "out/" 
          # 服务器域名
          REMOTE_HOST: "119.28.5.173" 
          # 腾讯云默认用户名为root
          REMOTE_USER: "chungguo" 
          # 目标目录
          TARGET: "/data/chungguo.github.io/out" 
        

